config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'bookmarks#index'
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def show 
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark
    else
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    if @bookmark.update(bookmark_params)
      redirect_to @bookmark
    else
      render :edit
    end  
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to root_path
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:title, :url, :rating)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with model: @bookmark do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %><br>
  </div>

  <div>
    <%= form.label :url %><br>
    <%= form.text_field :url %><br>
  </div>

  <div>
    <%= form.label :rating %><br>
    <%= form.radio_button :rating, 0 %>
    <%= form.label :rating_0, "0" %>
    <%= form.radio_button :rating, 1 %>
    <%= form.label :rating_1, "1" %>
    <%= form.radio_button :rating, 2 %>
    <%= form.label :rating_2, "2" %>
    <%= form.radio_button :rating, 3 %>
    <%= form.label :rating_3, "3" %>
    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>
<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/index.html.erb
<h1>All Bookmark</h1>
<table>
  <tr>
    <th>Title</th>
    <th>URL</th>
    <th>Rating</th>
    <th>Action</th>
  </tr>

  <% @bookmarks.each do |bookmark| %>
    <tr>
      <td><%= link_to bookmark.title, bookmark %></td>
      <td><%= bookmark.url %></td>
      <td><%= bookmark.rating %>/3</td> 
      <td>
        <%= link_to "Edit", controller: "bookmarks", action: "edit", id: bookmark.id%>
        <%= link_to "Delete", bookmark, method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= form_with model: @bookmark do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %><br>
  </div>

  <div>
    <%= form.label :url %><br>
    <%= form.text_field :url %><br>
  </div>

  <div>
    <%= form.label :title %><br>
    <%= form.number_field :rating %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.title %></h1>

<p>URL: <%= @bookmark.url %></p>
<p>Rating: <%= @bookmark.rating %>/3</p>
<p><%= link_to "Destroy", bookmark_path(@bookmark),
  method: :delete,
  data: { confirm: "Are you sure?" } %></p>
<p><%= link_to "Edit", edit_bookmark_path(@bookmark) %></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "New", new_bookmark_path %></li>
    </ul>
  </nav>
</footer>
<%= debug(params) if Rails.env.development? %>

app/views/layouts/_header.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h4 class="text-white">Collapsed content</h4>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booksmark</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/shim' %>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>